version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "${OPENVPN_VPN_PORT_EXTERNAL}:1194/udp"
    restart: always
    volumes:
     - ${OPENVPN_DATA_DIR_EXTERNAL}:/etc/openvpn
  